# TODO
**BE SURE TO ADD PATH TO `src/*` TO YOUR `ENVIROMENT/LIB/PYTHONVESRION/SITEPACKAGE/tnn.pth`** !
# Introduction to Tree NN

## Trees and DecisionUnits

In [15]:
from tnn import DecisionUnit, Tree
import torch
import torch.nn as nn

# simple model
class Double(nn.Module):
    def forward(self, x):
        return 2 * x

# tree either doubles x or leaves it
tree= Tree(1, 2, [nn.Identity(), Double()])
tree

Tree(
  (distribution): DecisionUnit(
    (linear): Linear(in_features=1, out_features=2, bias=True)
    (softmax_dim1): Softmax(dim=1)
    (softmax_dim0): Softmax(dim=0)
  )
)

Lets sample a few outputs of this simple tree and calculate E(x)

In [25]:
x = torch.ones((1,))
print(f"input = {x}")
for i in range(5):
    print(tree(x, select_max=False))

E = tree.expected_value(lambda z : z, x)
print(f"E(Tree(x)) = {E}")

input = tensor([1.])
tensor([2.])
tensor([2.])
tensor([2.])
tensor([1.])
tensor([2.])
E(Tree(x)) = tensor([1.7188], grad_fn=<AddBackward0>)


tensor([1.])