Kako dela autograd: 

In [2]:
import torch
import torch.nn as nn
from models import FeedForward


model = FeedForward(2, 2, 1)
list(model.parameters())

[Parameter containing:
 tensor([[0.3913, 0.1506],
         [0.5278, 0.3653]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5497, -0.4940], requires_grad=True),
 Parameter containing:
 tensor([[0.6631, 0.0845]], requires_grad=True),
 Parameter containing:
 tensor([-0.0214], requires_grad=True)]

In [11]:
x = torch.ones((2))
print(model(x, training=True))

# množimo iz desne s transposed matriko. TO je isto, kot če bi množil vrstico z vrstico
torch.dot(list(model.parameters())[0][0], x) + list(model.parameters())[1][0]

[tensor([1.0916, 0.3991], grad_fn=<ViewBackward0>), tensor([1.0916, 0.3991], grad_fn=<ReluBackward0>), tensor([1.2129, 0.4435], grad_fn=<MulBackward0>), tensor([0.8202], grad_fn=<ViewBackward0>)]


tensor(1.0916, grad_fn=<AddBackward0>)

[tensor([1.0916, 0.3991], grad_fn=<ViewBackward0>),
 tensor([1.0916, 0.3991], grad_fn=<ReluBackward0>),
 tensor([1.2129, 0.4435], grad_fn=<MulBackward0>),
 tensor([0.8202], grad_fn=<ViewBackward0>)]