In [ ]:
import torch 
from tnn import DecisionUnit

batch = torch.tensor([[i, 2*i, 3*i] for i in range(4)], dtype= torch.float)
print("batch:\n", batch)

d = DecisionUnit(3, 2)
probs = d(batch)
probs = torch.tensor([[1 + i, 0 + i] for i in range(4)], dtype= torch.float)
print("probs for two different branches (brach 1 has probability 1):\n", probs)

# batch, mapped by different branches
# b1 sums the row
# b2 returns 0 for each row
b1 = lambda x : torch.zeros((x.shape[0], 1)) + 1
b2 = lambda x : torch.zeros((x.shape[0], 1)) -1
branches = torch.stack([b1(batch), b2(batch)])
print("outputs of different branches\n" , branches)


probs_t = probs.transpose(0,1)
E = branches * probs_t.unsqueeze(2)

print("branches * probs:\n", E, "\nof shape", E.shape )

#E = torch.reshape(E, (4, 2))
E.sum(dim=1)


batch:
 tensor([[0., 0., 0.],
        [1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])
probs for two different branches (brach 1 has probability 1):
 tensor([[1., 0.],
        [2., 1.],
        [3., 2.],
        [4., 3.]])
outputs of different branches
 tensor([[[ 1.],
         [ 1.],
         [ 1.],
         [ 1.]],

        [[-1.],
         [-1.],
         [-1.],
         [-1.]]])
branches * probs:
 tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[-0.],
         [-1.],
         [-2.],
         [-3.]]]) 
of shape torch.Size([2, 4, 1])


tensor([ 3.,  7., -1., -5.])

Kako dela autograd: 

In [1]:
import torch
import torch.nn as nn
from models import FeedForward


model = FeedForward(2, 2, 1)
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5200,  0.0397],
         [ 0.4938, -0.6666]], requires_grad=True),
 Parameter containing:
 tensor([0.6722, 0.1079], requires_grad=True),
 Parameter containing:
 tensor([[-0.1349,  0.3691]], requires_grad=True),
 Parameter containing:
 tensor([0.4685], requires_grad=True)]

In [11]:
x = torch.ones((2))
print(model(x, training=True))

# množimo iz desne s transposed matriko. TO je isto, kot če bi množil vrstico z vrstico
torch.dot(list(model.parameters())[0][0], x) + list(model.parameters())[1][0]

[tensor([-0.9274, -0.4060], grad_fn=<ViewBackward0>), tensor([0., 0.], grad_fn=<ReluBackward0>), tensor([0., 0.], grad_fn=<MulBackward0>), tensor([-0.0010], grad_fn=<ViewBackward0>)]


tensor(-0.9274, grad_fn=<AddBackward0>)

Lets use grad

In [12]:

grads = torch.autograd.grad(
outputs=model(x),
inputs=[p for p in model.parameters() if p.requires_grad],
create_graph=True  # allows you to compute gradients of this gradient
)
grads

(tensor([[0., 0.],
         [0., 0.]], grad_fn=<TBackward0>),
 tensor([0., 0.], grad_fn=<ViewBackward0>),
 tensor([[0., 0.]], grad_fn=<TBackward0>),
 tensor([1.]))

In [15]:
g = grads[0]
torch.relu(1-torch.norm(g, dim=0))


tensor([1., 1.], grad_fn=<ReluBackward0>)